source 'https://rubygems.org'

ruby '>= 3.2.0'

gem 'rails', '~> 7.1.0'
gem 'sqlite3', '~> 1.4'
gem 'puma', '~> 6.4'
gem 'bootsnap', require: false
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'csv'
gem 'fiddle'
gem 'sprockets-rails'
gem 'sassc-rails'
gem 'importmap-rails'
gem 'jsbundling-rails'
gem 'cssbundling-rails'

# Spree Commerce
gem 'spree', '~> 4.8'
gem 'spree_backend', '~> 4.8'
gem 'spree_auth_devise', '~> 4.6'
gem 'spree_gateway', '~> 3.11'
gem 'spree_i18n', '~> 5.3'
gem 'deface'

# API
gem 'rack-cors'
gem 'jsonapi-serializer'

# Background jobs
gem 'sidekiq', '~> 7.2'

# Image processing
gem 'image_processing', '~> 1.12'

group :development, :test do
  gem 'byebug'
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem 'faker'
end

group :development do
  gem 'listen'
  gem 'spring'
end
